version: "3.9"

services:

  postgres:
    container_name: survivor_db
    image: postgres:14.2
    environment:
      POSTGRES_DB: survivor_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - survivor-postgres:/var/lib/postgresql/data


  survivor:
    container_name: survivor-app
    command: "bundle exec rails server -p 3000 -b '0.0.0.0'"
    # entrypoint: ["tail", "-f", "/dev/null"]
    build:
      context: .
      dockerfile: ./Dockerfile.local
    volumes:
      - .:/survivor
    links:
      - postgres
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    stdin_open: true
    tty: true

volumes:
  survivor-postgres: